version: '3'
services:
  frontend:
    build: ./front_end/
    ports:
      - "8080:80"
  backend:
    depends_on:
      - db
    build: ./backend/
    ports:
      - "8001:8001"
    environment:
      DJANGO_SETTINGS_MODULE: trascendence.settings
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres